### ISSUE TITLE
Property User.email incorrect

### ISSUE THREAD

**Issue by ligon** [hschafer/edstem#11]
diff --git a/edstem/user.py b/edstem/user.py
index 3d7f3d6..ebb492f 100644
--- a/edstem/user.py
+++ b/edstem/user.py
@@ -62,7 +62,7 @@ class User(base.EdObject[base.UserID]):
 
     @property
     def email(self) -> str:
-        return self._data["name"]
+        return self._data["email"]

**Comment by hschafer** [comment]
Thanks for catching this! This repo is still under development (and I've had a break from it for a while), but I'll fix this right now.

I'll mention that we have a more stable version of a Python wrapper for the API [here](https://github.com/hschafer/teaching-toolshed/blob/main/teachingtoolshed/api/edstem.py) and are working on this one to provide some better abstractions on the API.

**Comment by ligon** [comment]
Thanks!  I'll take a look at the 'toolshed', but this has already been very
helpful.
